# üìÖ Dia 7/100 ‚Äî Desafio 100 Dias de C√≥digo

Hoje foi o dia de aprender a **lidar com erros em Python** usando blocos `try`, `except`.

Fiz exerc√≠cios simulando situa√ß√µes comuns, como divis√µes por zero e acesso a √≠ndices inexistentes em listas. Aprender a capturar e tratar esses erros √© fundamental para criar programas mais robustos e √† prova de falhas.

No pr√≥ximo passo, vou explorar o uso de `finally`, `else` e exce√ß√µes personalizadas. Um passo essencial para qualquer desenvolvedor que quer escrever c√≥digo limpo e resiliente!
